module WxCardStatus

  #待审核
  CARD_STATUS_NOT_VERIFY = "CARD_STATUS_NOT_VERIFY"

  # 审核失败
  CARD_STATUS_VERIFY_FALL = "CARD_STATUS_VERIFY_FALL"

  #通过审核
  CARD_STATUS_VERIFY_OK = "CARD_STATUS_VERIFY_OK"

  #卡券被用户删除
  CARD_STATUS_USER_DELETE = "CARD_STATUS_USER_DELETE"

  #在公众平台投放过的卡券
  CARD_STATUS_USER_DISPATCH = "CARD_STATUS_USER_DISPATCH"


end